CREATE TABLE IF NOT EXISTS users (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`full_name` TEXT NOT NULL,
	`email` TEXT NOT NULL,
	`password` TEXT NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

	UNIQUE(email COLLATE NOCASE)
);
